node {
   // stages {
		stage('Preparation') { // for display purposes
			// Get some code from a GitHub repository
			 //[name: '*/master']  or   [name: '*/main']
				checkout([$class: 'GitSCM', branches: [[name: '*/master']],doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [],userRemoteConfigs: [[credentialsId: 'd1e418f5-e8f8-4cdf-8fc0-5100718ac544', url:'https://github.com/wenanlin/jenkins_tomcat_test.git']]])

		}
		stage('Build') {
			echo '拉取代码'
			sh label: '', script: 'mvn clean package'
		}
		stage('Results') {
		   echo '拉取代码'
		   deploy adapters: [tomcat8(credentialsId: '05c910e9-c1bf-4440-ad92-29def52021a7', path: '', url: 'http://192.168.10.12:8080/')], contextPath: '',war: 'target/*.war'

		}
	//}
}

